### PR TITLE
feat: add sticky menu

### PR DESCRIPTION
**Pull request by gaeljacquin**

### CODE REVIEW

**Comment by davidli3100** [comment]
Is this feature ready for review?

**Comment by gaeljacquin** [comment]
Yes it's ready for review. I don't have the option to request a review and assign someone.

**Review by jhthenerd — APPROVED** [review]
I did some testing, it seems to work fine. Could you also add this patch to the PR for Storybook? (I need to get around to adding the other parameters as knobs as well at some point)

```diff
diff --git a/src/components/A11yWrapper.stories.js b/src/components/A11yWrapper.stories.js
index 318fea8..98a8e8f 100644
--- a/src/components/A11yWrapper.stories.js
+++ b/src/components/A11yWrapper.stories.js
@@ -1,6 +1,6 @@
 import React from 'react';
 // eslint-disable-next-line import/no-extraneous-dependencies
-import { withKnobs, text } from '@storybook/addon-knobs';
+import { withKnobs, text, boolean } from '@storybook/addon-knobs';
 import A11yWrapper from '../index';
 
 export default {
@@ -10,7 +10,7 @@ export default {
 
 export const a11yWrapper = () => {
   return (
-    <A11yWrapper>
+    <A11yWrapper sticky={boolean('sticky', false)}>
       <h1>{text('Heading 1', 'This is Heading 1')}</h1>
       <h2>{text('Heading 2', 'This is Heading 2')}</h2>
       <h3>{text('Heading 3', 'This is Heading 3')}</h3>
```

**Review by davidli3100 — COMMENTED** [review]
Did a quick build and it looks good. One minor detail (if you want to figure this out) is that `position: sticky` isn't supported for Internet Explorer 10+.

If you want to work out a solution to have the sticky menu be back compatible that would be great

**Comment by gaeljacquin** [comment]
@davidli3100 The storybook (both my fork & upstream) is stuck on the loading animation in IE11.

ie11

And the sticky menu somehow still works when I change the user agent to IE10, in both Chrome & Edge.

**Comment by gaeljacquin** [comment]
@jhthenerd I applied the patch.

**Comment by err53** [comment]
I think we all forgot about this PR for like a year, sorry about that. I think we can go ahead and merge since this shouldn't break anything, any thoughts @davidli3100

**Pull request merged**
